namespace Trifling.Common.UnitTests.Compression
{
    using System.IO.Compression;

    using Microsoft.VisualStudio.TestTools.UnitTesting;

    using Trifling.Compression;
    using Trifling.Compression.Factory;
    using Trifling.Compression.Impl;
    using Trifling.Compression.Interfaces;

    /// <summary>
    /// Unit Tests for the <see cref="CompressorFactory"/> class. 
    /// </summary>
    [TestClass]
    public class CachedCompressorFactoryTests
    {
        [TestMethod]
        public void CachedCompressorFactory_Create_WhenIGzipCompressor_ThenReturnsGzipCompressor()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var configuration = new CompressorConfiguration();

            // ----- Act -----
            var instance = factory.Create<IGzipCompressor>(configuration);

            // ----- Assert -----
            Assert.IsNotNull(instance, "no implementation was generated.");
            Assert.IsInstanceOfType(instance, typeof(GzipCompressor), "the wrong type was generated by the factory.");
        }

        [TestMethod]
        public void CachedCompressorFactory_Create_WhenIDeflateCompressor_ThenReturnsDeflateCompressor()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var configuration = new CompressorConfiguration();

            // ----- Act -----
            var instance = factory.Create<IDeflateCompressor>(configuration);

            // ----- Assert -----
            Assert.IsNotNull(instance, "no implementation was generated.");
            Assert.IsInstanceOfType(instance, typeof(DeflateCompressor), "the wrong type was generated by the factory.");
        }

        [TestMethod]
        [ExpectedException(typeof(System.InvalidOperationException))]
        public void CachedCompressorFactory_Create_WhenICompressor_ThenThrowsException()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var configuration = new CompressorConfiguration();

            // ----- Act -----
            var instance = factory.Create<ICompressor>(configuration);

            // ----- Assert -----
            Assert.Fail("The expected exception was not thrown.");
        }

        [TestMethod]
        public void CachedCompressorFactory_Create_WhenCalledMultipleTimes_ThenSameInstanceReturned()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var configuration = new CompressorConfiguration();

            // ----- Act -----
            var firstInstance = factory.Create<IDeflateCompressor>(configuration);
            var secondInstance = factory.Create<IDeflateCompressor>(configuration);

            // ----- Assert -----
            Assert.AreSame(firstInstance, secondInstance, "The same instance was not returned (second instance is unique).");
        }

        [TestMethod]
        public void CachedCompressorFactory_Create_WhenCalledWithDifferentConfiguration_ThenDifferentInstanceReturned()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var firstConfiguration = new CompressorConfiguration(400, CompressionLevel.Optimal);
            var secondConfiguration = new CompressorConfiguration(200, CompressionLevel.Optimal);

            // ----- Act -----
            var firstInstance = factory.Create<IGzipCompressor>(firstConfiguration);
            var secondInstance = factory.Create<IGzipCompressor>(secondConfiguration);

            // ----- Assert -----
            Assert.AreNotSame(firstInstance, secondInstance, "The same instance was returned for different configurations.");
        }

        [TestMethod]
        public void CachedCompressorFactory_Create_WhenCalledWithDifferentConfiguration2_ThenDifferentInstanceReturned()
        {
            // ----- Arrange -----
            var factory = new CachedCompressorFactory();
            var firstConfiguration = new CompressorConfiguration(300, CompressionLevel.Fastest);
            var secondConfiguration = new CompressorConfiguration(300, CompressionLevel.Optimal);

            // ----- Act -----
            var firstInstance = factory.Create<IDeflateCompressor>(firstConfiguration);
            var secondInstance = factory.Create<IDeflateCompressor>(secondConfiguration);

            // ----- Assert -----
            Assert.AreNotSame(firstInstance, secondInstance, "The same instance was returned for different configurations.");
        }
    }
}
